# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea7808c8bd3d21664342826dbe2912a65b1a9441050db599b0ac6f67e64879ba9f6974be732d9d2217d50d6816992b60d1feb815f45b5fee8c21dc95ff3927c

test:
  secret_key_base: 8055773154cf459a16b9e383b0952bd5e5e2209c59e89da7014947022401e640b64e02f09ff125d04d0f0c81493d637308013219320a325d75c71a47804cbba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
